# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-01 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 20, 54, 4, 691561), verbose_name='添加时间'),
        ),
    ]
