# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-21 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190901_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 10, 29, 9, 445808), verbose_name='添加时间'),
        ),
    ]
